/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Truck } from "./Truck";
import { TruckCountArgs } from "./TruckCountArgs";
import { TruckFindManyArgs } from "./TruckFindManyArgs";
import { TruckFindUniqueArgs } from "./TruckFindUniqueArgs";
import { CreateTruckArgs } from "./CreateTruckArgs";
import { UpdateTruckArgs } from "./UpdateTruckArgs";
import { DeleteTruckArgs } from "./DeleteTruckArgs";
import { TripFindManyArgs } from "../../trip/base/TripFindManyArgs";
import { Trip } from "../../trip/base/Trip";
import { TruckService } from "../truck.service";
@graphql.Resolver(() => Truck)
export class TruckResolverBase {
  constructor(protected readonly service: TruckService) {}

  async _trucksMeta(
    @graphql.Args() args: TruckCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Truck])
  async trucks(@graphql.Args() args: TruckFindManyArgs): Promise<Truck[]> {
    return this.service.trucks(args);
  }

  @graphql.Query(() => Truck, { nullable: true })
  async truck(
    @graphql.Args() args: TruckFindUniqueArgs
  ): Promise<Truck | null> {
    const result = await this.service.truck(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Truck)
  async createTruck(@graphql.Args() args: CreateTruckArgs): Promise<Truck> {
    return await this.service.createTruck({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Truck)
  async updateTruck(
    @graphql.Args() args: UpdateTruckArgs
  ): Promise<Truck | null> {
    try {
      return await this.service.updateTruck({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Truck)
  async deleteTruck(
    @graphql.Args() args: DeleteTruckArgs
  ): Promise<Truck | null> {
    try {
      return await this.service.deleteTruck(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Trip], { name: "trips" })
  async findTrips(
    @graphql.Parent() parent: Truck,
    @graphql.Args() args: TripFindManyArgs
  ): Promise<Trip[]> {
    const results = await this.service.findTrips(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
